### ISSUE TITLE
( iP4S iOS 7.0.4 ) Couria 0.6~beta4-1 doesn't display pop up for QR & QC

### ISSUE THREAD

**Issue by DarkXShadowX21** [Qusic/Couria#15]
Hello,

I've tried using the tweak from your beta repo for sometime. I have not seen the pop display once for me since I've had it. I'm not sure why this would be. I understand this extension is still in beta but I've read from other users that it does work. 

Any help on resolving this would be great. Thanks!

**Comment by rajlee** [comment]
Couria isn't working from pulling it down from top notification plz advise me

**Comment by rajlee** [comment]
I meant from the top banner I couria won't open by dragging it down
