### ISSUE TITLE
Third party extensions don't work with some notifications

### ISSUE THREAD

**Issue by DavidGoldman** [Qusic/Couria#29]
Notifications that have a pulldownView don't appear to work at the moment- the normal pulldown view shows instead of Couria. 

Example app: Facebook Messenger

EDIT: Not sure if this is intentional or not - perhaps this should be an option?

**Comment by Qusic** [comment]
sorry I dont use Facebook Messenger and am not able to test it myself. btw what kind of pulldownView does it have? If it is just one or two buttons it should work.

**Comment by DavidGoldman** [comment]
Yeah the pulldown has two buttons. Am able to reproduce it with GroupMe (try messaging apps) and did confirm that the code otherwise works fine by changing the extension id temporarily to snapchat.

**Comment by Qusic** [comment]
fixed.
