### ISSUE TITLE
Messages Received While Screen Locked Marked Read Since 0.8.1 Update

### ISSUE THREAD

**Issue by lmkunert** [Qusic/Couria#30]
I get notifications on my Pebble for messages, but they show up and disappear immediately on my lockscreen and are even marked read now ever since updating to 0.8.1 of Couria two nights ago. Very odd and wasn't doing this until I updated. Very disconcerting since I'm not getting texts and don't see them if my Pebble gets wonky and doesn't send notification as well. Have missed some today already.

**Comment by lmkunert** [comment]
I see 0.8.2 is supposed to fix this actually. :)

**Comment by Qusic** [comment]
please update to the latest version
