### ISSUE TITLE
QC in Couria coming up blank with no keyboard or contact list

### ISSUE THREAD

**Issue by frozinwater** [Qusic/Couria#33]
Whenever I attempt to use quick compose, it comes up blank with an icon on the top of the screen saying new message without a keyboard or a contact list. I have it set to allow contacts and pictures and I still get the same issue. I have also attempted to uninstall/reinstall multiple times. Any help would be greatly appreciated because I am very anxious to use QC and is one of the main reason I jailbroke in the first place. Thank you so much. 
![image](https://cloud.githubusercontent.com/assets/16053386/11449321/43a5bdda-953e-11e5-888f-83a494abfe28.png)

**Comment by Qusic** [comment]
this should be fixed in 0.9.4
